version: '3.8'

services:
  max-node-app:
    container_name: sample-node-app
    build: .
    ports:
      - "3000:3000"
    environment:
      # DB_USERNAME: admin
      # DB_PASSWORD: Password1
      # DB_NAME: maxdb
      DB_HOST: mongodb:27017
      # DB_HOST: host.docker.internal:27017
    # networks:
    #   - existing-network-in-docker

# networks:
#   existing-network-in-docker:
#     external: true
